### ISSUE TITLE
Battery-icon.sh reports 10% instead of 100% when fully charged

### ISSUE THREAD

**Issue by Mrakor** [nwg-piotr/t2ec#1]
Hello,

I am on Arch linux. My acpi -b returns "Battery 0: Full, 100%" when fully charged.
acpi v. 1.7

At line 27: 
level=${level::-2} 100 gets truncated to 10

I am newbie in bash, so maybe my change to the script isn't best, but it seems to work:

        if [[ "$state" == *"Unknown"* ]]; then
            level=${level::-1}
        else
            if [[ "$level" == "100%" ]]; then
                level=100
            else
                level=${level::-2}
            fi
        fi

Anyway thank you for great collection of scripts.
Have a nice day.

**Comment by nwg-piotr** [comment]
Well, I'm slightly confused. It looks like this on my machine:

![image](https://user-images.githubusercontent.com/20579136/76144277-f291ab00-607e-11ea-85bf-75ef2a155d04.png)

**Comment by nwg-piotr** [comment]
Should be fixed now.
